### ISSUE TITLE
[back] Configure logging using a file in server directory

### ISSUE THREAD

**Issue by landerneRPi** [mdl29/scratchy#143]
Instead of a basic configuration, use a logging configuration defined in INI or YAML format.
Load this logging file and apply the configuration.
Example in YAML: logging.yaml  file
```

version: 1
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout"
loggers:
  werkzeug:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
```
Change into app.py:
```
...
import yaml
import logging

 with open('logging.yaml', 'r') as logging_file:
    config_logging = yaml.load(logging_file, Loader=yaml.FullLoader)

 logging.config.dictConfig(config_logging)
...

```
