### ISSUE TITLE
[deployment] Add Elasticsearch to docker environment

### ISSUE THREAD

**Issue by landerneRPi** [mdl29/scratchy#145]
Add Elasticsearch (for logs management) in EFK (Elasticsearch, Fluent, Kibana) stack.

Example in docker/docker-compose.yaml:
```
  elasticsearch:
    image: elasticsearch:7.12.1
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
          soft: -1
          hard: -1
    user: 'elasticsearch'

```
