### ISSUE TITLE
[deployment] Add Kibana to docker environment

### ISSUE THREAD

**Issue by landerneRPi** [mdl29/scratchy#146]
Add Kibana (for logs management) in EFK (Elasticsearch, Fluent, Kibana) stack.

Example in docker/docker-compose.yaml (default configuration, connected to default Elasticsearch port):
```
   kibana:
    image: kibana:7.12.1
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

```
