### ISSUE TITLE
[deployment] Add Fluentd to docker environment

### ISSUE THREAD

**Issue by landerneRPi** [mdl29/scratchy#147]
Add Fluentd (for logs management) in EFK (Elasticsearch, Fluent, Kibana) stack.

Create a *Dockerfile* in *fluentd* directory to manage the Elasticsearch plugin for Fluentd.

Create in *docker/etc/fluentd* directory, the *fluentd.conf* file for managing source and Elasticsearch connection.

Example in docker/docker-compose.yaml:
```
  fluentd:
    build: ./fluentd
    volumes:
      - ./etc/fluentd:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
```
