### ISSUE TITLE
[deployment] Add scratchy to docker environment

### ISSUE THREAD

**Issue by landerneRPi** [mdl29/scratchy#150]
Add scratchy using docker image in *docker-compose.yaml* file (from Dockerfile in server directory):
* docker build -t scratchy-server:latest .

Use *fluentd* docker driver for logging, example:

```
  scratchy:
    image: scratchy-server:latest
    ports:
      - "5000:5000"
    links:
      - "mongodb"
    volumes:
      - ./etc/scratchy/config.json:/app/config.json
      - ./etc/scratchy/logging.yaml:/app/logging.yaml
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: scratchy.server
```
